
CREATE TABLE EMPLOYEE(
    ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    BIRTH_DATE DATE,
    SALARY DECIMAL,
    COMPANY_ID BIGINT,
    
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(ID)
);