    INSERT INTO COMPANY (NAME, COUNTRY) VALUES ('GAMA', 'POLAND');
    INSERT INTO COMPANY (NAME, COUNTRY) VALUES ('Infor', 'POLAND');
    INSERT INTO COMPANY (NAME, COUNTRY) VALUES ('Siemens', 'POLAND');
    INSERT INTO COMPANY (NAME, COUNTRY) VALUES ('Body', 'POLAND');