INSERT INTO EMPLOYEE (EMP_FIRST_NAME, EMP_LAST_NAME, EMP_BIRTH_DATE, EMP_SALARY, COMP_ID)
    VALUES ('Kris', 'Gala', '1995-04-11', 5000.0, 1);
INSERT INTO EMPLOYEE (EMP_FIRST_NAME, EMP_LAST_NAME, EMP_BIRTH_DATE, EMP_SALARY, COMP_ID)
    VALUES ('Ann', 'Smith', '1991-04-22', 2000.0, 1);
INSERT INTO EMPLOYEE (EMP_FIRST_NAME, EMP_LAST_NAME, EMP_BIRTH_DATE, EMP_SALARY, COMP_ID)
    VALUES ('Emma', 'Johnson', '1990-01-11', 15000.5, 1);